"""Generate checked v1 OpenAPI and TypeScript wire types from that one authority."""

from __future__ import annotations

import argparse
import hashlib
import json
import tempfile
from pathlib import Path

from nfl_fantasy_assistant.api import create_app
from nfl_fantasy_assistant.config import generate_token


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--openapi", type=Path, required=True)
    parser.add_argument("--typescript", type=Path, required=True)
    arguments = parser.parse_args()
    with tempfile.TemporaryDirectory() as temporary:
        app = create_app(
            Path(temporary) / "contract.sqlite3",
            generate_token(),
            "chrome-extension://abcdefghijklmnopabcdefghijklmnop",
        )
        payload = json.dumps(app.openapi(), indent=2, sort_keys=True).encode() + b"\n"
    document = json.loads(payload)
    digest = hashlib.sha256(payload).hexdigest()
    arguments.openapi.write_bytes(payload)
    arguments.typescript.write_text(_typescript(document, digest), encoding="utf-8")


def _typescript(document: dict[str, object], digest: str) -> str:
    schemas = document["components"]["schemas"]  # type: ignore[index]
    lines = [
        "// Generated by backend/scripts/generate_openapi.py; do not edit.",
        f'export const openapiContractSha256 = "{digest}" as const;',
        "",
        "export interface components {",
        "  schemas: {",
    ]
    for name, schema in schemas.items():  # type: ignore[union-attr]
        lines.append(f'    "{name}": {_type(schema)};')
    lines.extend(["  };", "}", "", "export interface paths {"])
    for path, item in document["paths"].items():  # type: ignore[index,union-attr]
        lines.append(f'  "{path}": {{')
        for method, operation in item.items():  # type: ignore[union-attr]
            lines.append(f"    {method}: {_operation_type(operation)};")
        lines.append("  };")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _operation_type(operation: object) -> str:
    if not isinstance(operation, dict):
        return "never"
    request_body = operation.get("requestBody")
    response = operation.get("responses", {}).get("200")
    request_type = _content_type(request_body) if isinstance(request_body, dict) else "never"
    response_type = _content_type(response) if isinstance(response, dict) else "never"
    return f"{{ request: {request_type}; response: {response_type} }}"


def _content_type(container: dict[str, object]) -> str:
    content = container.get("content")
    if not isinstance(content, dict):
        return "never"
    json_content = content.get("application/json")
    return _type(json_content.get("schema", {})) if isinstance(json_content, dict) else "never"


def _type(schema: object) -> str:
    if not isinstance(schema, dict):
        return "unknown"
    if "$ref" in schema:
        return 'components["schemas"]["' + str(schema["$ref"]).split("/")[-1] + '"]'
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    for union_name in ("anyOf", "oneOf", "allOf"):
        if union_name in schema:
            return " | ".join(_type(value) for value in schema[union_name])
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        return f"Array<{_type(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not isinstance(properties, dict):
            return "Record<string, unknown>"
        fields = " ".join(
            f'"{name}"{"" if name in required else "?"}: {_type(value)};'
            for name, value in properties.items()
        )
        return "{ " + fields + " }"
    return "unknown"


if __name__ == "__main__":
    main()
