// Generated by backend/scripts/generate_openapi.py; do not edit.
export const openapiContractSha256 = "cfca53fa05c55a91aa894d0666469a75267914edcd8124cc87b4dde9761b6046" as const;

export interface components {
  schemas: {
    "ComponentReadiness": { "detail": string; "status": "ready" | "unavailable" | "degraded"; };
    "DiagnosticsResponse": { "adapter": components["schemas"]["ComponentReadiness"]; "api_version": string; "data": components["schemas"]["ComponentReadiness"]; "database": components["schemas"]["ComponentReadiness"]; "identity": components["schemas"]["ComponentReadiness"]; "recommendations": components["schemas"]["ComponentReadiness"]; };
    "DraftCreateRequest": { "config": components["schemas"]["LeagueConfigInput"]; "dataset_version": string; "draft_order": Array<string>; "feature_version": string; "initial_picks"?: Array<components["schemas"]["ObservedPickInput"]>; "league_id": string; "model_version": string; "provider": string; "provider_draft_id": string; "user_slot": number; "user_team_id": string; };
    "DraftStateResponse": { "accepted_picks": number; "current_pick": number; "dataset_version": string; "draft_id": string; "feature_version": string; "issues": Array<string>; "league_id": string; "model_version": string; "reconciliation_state": string; "revision": number; "status": string; "unresolved_observations": number; };
    "ErrorBody": { "code": string; "details"?: {  }; "message": string; "request_id": string; "retryable": boolean; };
    "ErrorEnvelope": { "error": components["schemas"]["ErrorBody"]; };
    "EventRequest": { "event_id": string; "league_provider": string; "observed_at": string; "pick": components["schemas"]["ObservedPickInput"]; "protocol_version"?: string; "surface": "espn" | "fantasypros"; "type": string; };
    "EventResponse": { "draft": components["schemas"]["DraftStateResponse"]; "outcome": string; "replayed": boolean; "revision": number; };
    "HTTPValidationError": { "detail"?: Array<components["schemas"]["ValidationError"]>; };
    "HealthResponse": { "api_version": string; "status": string; };
    "LeagueConfigInput": { "config_version": string; "draft_type": string; "roster_slots": Array<components["schemas"]["RosterSlotInput"]>; "scoring_rules"?: {  }; "superflex"?: boolean; "te_premium"?: number; "team_count": number; };
    "LeagueCreateRequest": { "config": components["schemas"]["LeagueConfigInput"]; "provider": string; "provider_league_id": string; };
    "LeagueResponse": { "config_version": string; "league_id": string; };
    "ObservedPickInput": { "overall_pick": number; "player": components["schemas"]["PlayerReferenceInput"]; "team_id": string; };
    "PlayerReferenceInput": { "external_id": string; "name"?: string | unknown; "nfl_team"?: string | unknown; "position"?: "QB" | "RB" | "WR" | "TE" | "K" | "DEF" | unknown; "provider": string; };
    "RecommendationCandidateResponse": { "components": {  }; "confidence": number; "draft_score": number; "internal_player_id": string; "rank": number; "reason_codes": Array<string>; "reason_text": string; "warnings": Array<string>; };
    "RecommendationResponse": { "candidates": Array<components["schemas"]["RecommendationCandidateResponse"]>; "dataset_version": string; "draft_id": string; "feature_version": string; "generated_at": string; "model_version": string; "revision": number; "source_updated_at": {  }; "status": string; };
    "RosterSlotInput": { "eligible_positions": Array<"QB" | "RB" | "WR" | "TE" | "K" | "DEF">; "is_bench"?: boolean; "name": string; };
    "SnapshotRequest": { "declared_complete": boolean; "observed_at": string; "picks": Array<components["schemas"]["ObservedPickInput"]>; "source": "espn" | "fantasypros"; };
    "SnapshotResponse": { "differences": {  }; "draft": components["schemas"]["DraftStateResponse"]; "outcome": string; "revision": number; };
    "ValidationError": { "ctx"?: {  }; "input"?: unknown; "loc": Array<string | number>; "msg": string; "type": string; };
  };
}

export interface paths {
  "/v1/diagnostics": {
    get: { request: never; response: components["schemas"]["DiagnosticsResponse"] };
  };
  "/v1/drafts": {
    post: { request: components["schemas"]["DraftCreateRequest"]; response: components["schemas"]["DraftStateResponse"] };
  };
  "/v1/drafts/{draft_id}": {
    get: { request: never; response: components["schemas"]["DraftStateResponse"] };
  };
  "/v1/drafts/{draft_id}/events": {
    post: { request: components["schemas"]["EventRequest"]; response: components["schemas"]["EventResponse"] };
  };
  "/v1/drafts/{draft_id}/recommendations": {
    get: { request: never; response: components["schemas"]["RecommendationResponse"] };
  };
  "/v1/drafts/{draft_id}/snapshot": {
    post: { request: components["schemas"]["SnapshotRequest"]; response: components["schemas"]["SnapshotResponse"] };
  };
  "/v1/health": {
    get: { request: never; response: components["schemas"]["HealthResponse"] };
  };
  "/v1/leagues": {
    post: { request: components["schemas"]["LeagueCreateRequest"]; response: components["schemas"]["LeagueResponse"] };
  };
}
